name: project-management-mcp-server

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: coupang_dev
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: docker
      dockerfile: ./prod/Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
